/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;


/**
 *
 * @author Diego RM
 */
public class Lienzo extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form Lienzo
     */
    int x = getWidth() / 2;
    Thread hilo1;

    public Lienzo() {
        initComponents();
        hilo1 = new Thread(this);
    }

    public void paint(Graphics graficos) {

        //Repintar nuestra pelota 
        graficos.setColor(getBackground());
        graficos.fillRect(0, 0, getWidth(), getHeight());
        graficos.setColor(Color.RED);
        graficos.fillOval(x, getHeight() / 2, 30, 30);

    }// Fin método paint

    public void inicio() {
        hilo1.start();
    }// Fin método inicio

    public void pausa() {
        hilo1.suspend();
    }// Fin método pausa

    public void continuar() {
        hilo1.resume();
    }// Fin método continuar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {
        try {
            while (true) {
                while (x < getWidth() - 30) {
                    Thread.sleep(50);
                    x += 10;
                    repaint();
                }// Fin mover derecha
                while (x > 10) {
                    Thread.sleep(50);
                    x -= 10;
                    repaint();
                }// Fin mover izquierda
            }
        } catch (Exception e) {
            System.out.println("ERROR001: " + e.getMessage());
        }
    }
}
